Graduate/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django.urls import path, include, re_path
from Graduate import settings
from Graduate.settings import MEDIA_ROOT
from app01.views.everyone import login, register
from app01.views.student import student, student_echarts
from app01.views.teacher import teacher, teacher_echarts, teacher_notice
from app01.views.tools import tools
from app01.views.tools import *

urlpatterns = [
                  path('', login.login),
                  re_path(r'^api/', include('app01.api-urls')),
                  path("admin/", admin.site.urls),
                  path('register/', register.register),
                  path('error/', tools.error),
                  path('captcha/', include('captcha.urls')),
                  path('refresh_captcha/', tools.refresh_captcha, name='refresh_captcha'),
                  # 学生登录页面
                  path('student/index/', student.stu_index),
                  path('student/edit/password/', student.student_edit_password),
                  path("student/forgetpasswd/", student.student_forgetpasswd),
                  path('reset-student-password/<str:uidb64>/<str:token>/', student.reset_password,
                       name='reset-student-password'),
                  path('logout/', tools.logout),
                  path('student/china/', student_echarts.student_china),
                  path('student/get/china/data/', student_echarts.student_get_china_data),
                  path('student/notice/', student.student_notice),
                  path('student/get/notice/', student.student_get_notice),
                  path('student/xinzi/', student.xinzi),
                  path('student/dataTable/', student.dataTable),
                  path("student/dataView/", student.dataView),
                  path('student/chartsSkill/', student.chartsSkill),
                  path('student/chartsTags/', student.chartsTags),
                  path('student/chartsAddr/', student.chartsAddr),
                  path('student/chartsCompany/', student.chartsCompany),
                  path('student/kaoyan/', student.kaoyan),
                  path('student/calendar/', student.calendar),

                  # 学生清除红点
                  path('student/clear_notice/', student.student_clear_notice),
                  # 教师登陆
                  path('teacher/login/', teacher.teacher_login),
                  path("teacher/forgetpasswd/", teacher.teacher_forgetpasswd),
                  path('reset-teacher-password/<str:uidb64>/<str:token>/', teacher.reset_password,
                       name='reset-teacher-password'),
                  path('teacher_index/', teacher.teacher_index),
                  # 教师查看学生信息
                  path('teacher_student_views/', teacher.teacher_student_views),
                  path('teacher/edit/password/', teacher.teacher_edit_password),
                  path('teacher/add/', teacher.add_student),
                  path('teacher/delete/', teacher.delete_student),
                  path('get/edit_detail/', teacher.get_edit_detail),
                  path('teacher/student_edit/', teacher.teacher_student_edit),
                  # 教师管理班级信息
                  path('teacher_classes_views/', teacher.teacher_classes_views),
                  path('teacher/add/class/', teacher.add_class),
                  path('teacher/classes/delete/', teacher.delete_class),
                  path('get/classes/edit_detail/', teacher.get_classes_edit_detail),
                  path('teacher/classes_edit/', teacher.teacher_classes_edit),
                  # 教师页面查看班级以及学生的详情表
                  path('students/echarts/', teacher_echarts.students_echarts),
                  path('teacher_manage_classes/', teacher_echarts.teacher_manage_classes),
                  path('teacher_classes_status/', teacher_echarts.teacher_classes_status),
                  path('teacher/china/', teacher_echarts.teacher_china),
                  path('teacher/get/china/data/', teacher_echarts.teacher_get_china_data),
                  # 教师发布通知和管理通知
                  path('teacher/add/notice/', teacher_notice.add_notice),
                  path('teacher_manage/notice/', teacher_notice.manage_notice),
                  path('teacher/get/notice/edit_detail/', teacher_notice.get_notice_edit_detail),
                  path('teacher/notice/edit/', teacher_notice.teacher_notice_edit),
                  path('teacher/notice/delete/', teacher_notice.teacher_notice_delete),
                  # path(r'^static/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
                  path('static/<path:path>', serve, {'document_root': MEDIA_ROOT})
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = register.page_not_found

app01/models.py
from django.contrib.auth.hashers import make_password, check_password
from django.db import models

role = (
    (0, '老师'),
    (1, '学生'),
)


class Teacher(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=50, unique=True)
    phone = models.CharField(max_length=50, verbose_name='手机号', unique=True)
    password = models.CharField(verbose_name='密码', max_length=100)
    email = models.EmailField(null=True, blank=True, unique=True)
    avatar = models.ImageField(upload_to='teacher_images', null=True, blank=True, verbose_name='头像')
    role = models.IntegerField(verbose_name='角色', choices=role, default=0)
    last_login = models.DateTimeField(null=True, blank=True)

    def get_email_field_name(self):
        return 'email'

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "老师"
        verbose_name_plural = "老师"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)


class Class(models.Model):
    name = models.CharField(verbose_name='班级名', max_length=50, unique=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="负责的老师")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "班级"
        verbose_name_plural = "班级"


provinces = (
    (0, '北京市'),
    (1, '天津市'),
    (2, '河北省'),
    (3, '山西省'),
    (4, '内蒙古自治区'),
    (5, '辽宁省'),
    (6, '吉林省'),
    (7, '黑龙江省'),
    (8, '上海市'),
    (9, '江苏省'),
    (10, '浙江省'),
    (11, '安徽省'),
    (12, '福建省'),
    (13, '江西省'),
    (14, '山东省'),
    (15, '河南省'),
    (16, '湖北省'),
    (17, '湖南省'),
    (18, '广东省'),
    (19, '广西壮族自治区'),
    (20, '海南省'),
    (21, '重庆市'),
    (22, '四川省'),
    (23, '贵州省'),
    (24, '云南省'),
    (25, '西藏自治区'),
    (26, '陕西省'),
    (27, '甘肃省'),
    (28, '青海省'),
    (29, '宁夏回族自治区'),
    (30, '新疆维吾尔自治区'),
    (31, '台湾省'),
    (32, '香港特别行政区'),
    (33, '澳门特别行政区')
)


class Student(models.Model):
    student_no = models.CharField(max_length=50, unique=True, verbose_name='学号')
    username = models.CharField(max_length=50, verbose_name='用户名')
    phone = models.CharField(max_length=50, verbose_name='手机号', unique=True)
    password = models.CharField(max_length=100, verbose_name='密码')
    email = models.EmailField(null=True, blank=True, unique=True)
    classs = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='students', verbose_name='所在班级')
    avatar = models.ImageField(upload_to='app01/', default='app1/default_avatar.jpg', null=True, blank=True,
                               verbose_name='头像')
    status = models.IntegerField(verbose_name="毕业去向", choices=((0, '就业'), (1, '升学')), default=0)
    role = models.IntegerField(verbose_name='角色', choices=role, default=1)
    province = models.IntegerField(verbose_name='意向地区', choices=provinces, default=16)
    is_read = models.IntegerField(verbose_name="已未读", choices=((0, '未读'), (1, '已读')), default=0)
    last_login = models.DateTimeField(null=True, blank=True)

    def get_email_field_name(self):
        return 'email'

    def __str__(self):
        return self.student_no

    class Meta:
        verbose_name = "学生"
        verbose_name_plural = "学生"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)


class Notice(models.Model):
    title = models.CharField(verbose_name="标题", max_length=200)
    content = models.TextField(verbose_name="内容")
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='notices')
    classes = models.ManyToManyField(Class, related_name='notices', verbose_name='班级')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "通知"
        verbose_name_plural = "通知"



class JobInfo(models.Model):
    # model自增字段
    id = models.AutoField('id', primary_key=True)
    title = models.CharField('岗位名字', max_length=255, default='')
    address = models.CharField('省份', max_length=255, default='')
    type = models.CharField('职业', max_length=255, default='')
    educational = models.CharField('学历', max_length=255, default='')
    workExperience = models.CharField('工作经历', max_length=255, default='')
    workTag = models.CharField('工作标签', max_length=2555, default='')
    salary = models.CharField('薪资', max_length=255, default='')
    salaryMonth = models.CharField('年终奖', max_length=255, default='')
    companyTags = models.CharField('公司福利', max_length=2555, default='')
    hrWork = models.CharField('人事职位', max_length=255, default='')
    hrName = models.CharField('人事名字', max_length=255, default='')
    pratice = models.BooleanField('是否为实习单位', max_length=255, default='')
    companyTitle = models.CharField('公司名称', max_length=255, default='')
    companyAvatar = models.CharField('公司头像', max_length=255, default='')
    companyNature = models.CharField('公司性质', max_length=255, default='')
    companyStatus = models.CharField('公司状态', max_length=255, default='')
    companyPeople = models.CharField('公司人数', max_length=255, default='')
    detailUrl = models.CharField('详情地址', max_length=2555, default='')
    companyUrl = models.CharField('公司详情地址', max_length=2555, default='')
    createTime = models.DateField('创建时间', auto_now_add=True)
    dist = models.CharField('行政区', max_length=255, default='')

    def toDict(self):
        return {'title': self.title, 'address': self.address, 'type': self.type, 'educational': self.educational,
                'workExperience': self.workExperience, 'workTag': self.workTag, 'salary': self.salary,
                'salaryMonth': self.salaryMonth, 'companyTags': self.companyTags,'hrName': self.hrName.strip(self.hrWork),
                'hrWork': self.hrWork, 'pratice': self.pratice,'companyTitle': self.companyTitle,
                'companyAvatar': self.companyAvatar,'companyNature': self.companyNature, 'companyStatus': self.companyStatus,
                'companyPeople': self.companyPeople,'detailUrl':self.detailUrl,'companyUrl':self.companyUrl,
                'dist':self.dist}

    # 数据库的表名称
    class Meta:
        verbose_name = "招聘信息"
        verbose_name_plural = "招聘信息"


class School(models.Model):
    name = models.CharField(verbose_name="院校名称", max_length=32, null=True)
    location = models.CharField(verbose_name="所在地", max_length=32, null=True)
    department = models.CharField(verbose_name="院校隶属", max_length=32, null=True)
    department_choices = (

        (1, "研究生院"),
        (0, " ")
    )
    is_research = models.BooleanField(verbose_name="是否有研究生院", choices=department_choices, max_length=32,
                                      null=True)
    line_choices = (

        (1, "自划线"),
        (0, " ")
    )
    is_auto_line = models.BooleanField(verbose_name="是否为自划线院校", choices=line_choices, max_length=32, null=True)
    double_choices = (
        (1, "双一流"),
        (0, " ")
    )
    is_double_one = models.BooleanField(verbose_name="是否为双一流院校", choices=double_choices, max_length=32,
                                        null=True)
    icon = models.CharField(verbose_name="图标链接", max_length=255, default='')
    url = models.CharField(verbose_name="院校链接", max_length=255, default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "院校"
        verbose_name_plural = verbose_name

app01/templates/teacher/teacher_student_views.html
{% extends 'teacher/teacher_layout.html' %}
{% load static %}
{% block content %}
    <!-- 内容填充 -->
    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box justify-content-between d-flex align-items-md-center flex-md-row flex-column">
                            <h4 class="page-title">班级学生信息</h4>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <button id="btnAdd" class="btn btn-success btn-function" data-bs-toggle="modal"
                                        data-bs-target="#signup-modal">
                                    新增学生
                                </button>
                                <br>
                                <br>
                                <table id="alternative-page-datatable"
                                       class="table table-striped dt-responsive nowrap w-100 dataTable no-footer dtr-inline">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>学号</th>
                                        <th>用户</th>
                                        <th>密码</th>
                                        <th>手机号</th>
                                        <th>班级</th>
                                        <th>毕业去向</th>
                                        <th>意向城市</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for student in students %}
                                        <tr>
                                            <td>{{ student.id }}</td>
                                            <td>{{ student.student_no }}</td>
                                            <td><img src="/media/{{ student.avatar }}"
                                                     alt="table-user"
                                                     class="me-2 rounded-circle"
                                                     height="24"> {{ student.username }}</td>
                                            <td>******</td>
                                            <td>{{ student.phone }}</td>
                                            <td>{{ student.classs.name }}</td>
                                            <td>{{ student.get_province_display }}</td>
                                            <td>{{ student.get_status_display }}</td>
                                            <td>
                                                <button data-eid="{{ student.id }}"
                                                        class="btn btn-primary btn-sm btn-function btnEdit"
                                                        data-bs-toggle="modal" data-bs-target="#signup-modal">
                                                    编辑
                                                </button>
                                                <button data-id="{{ student.id }}"
                                                        class="btn btn-danger btn-sm btnDelete"
                                                        data-bs-toggle="modal" data-bs-target="#fill-danger-modal">删除
                                                </button>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                                <!-- 编辑、新增模态框 -->
                                <div id="signup-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="multiple-oneModalLabel">新增</h4>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <form id="addForm" action="#" novalidate
                                                      class="ps-3 pe-3">

                                                    {% for field in form %}
                                                        <div class="mb-3" style="position: relative">
                                                            <label class="form-label">{{ field.label }}</label>
                                                            {{ field }}
                                                            <span class="s_error"
                                                                  style="color:red;position: absolute">{{ field.errors.0 }}</span>
                                                        </div>
                                                    {% endfor %}
                                                    <div class="mb-3 text-center">
                                                        <button type="button" class="btn rounded-pill btn-light"
                                                                data-bs-dismiss="modal">关闭
                                                        </button>

                                                        <input type="button" class="btn rounded-pill btn-primary"
                                                               id="btnSave" value="保存"/>
                                                    </div>
                                                </form>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->

                                <!-- 删除模态框 -->
                                <div id="fill-danger-modal" class="modal fade" tabindex="-1" role="dialog"
                                     aria-labelledby="danger-header-modalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content modal-filled bg-danger">
                                            <div class="modal-header modal-colored-header bg-danger">
                                                <h4 class="modal-title" id="danger-header-modalLabel">警告</h4>
                                                <button type="button" class="btn-close btn-close-white"
                                                        data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <h5 class="mt-0">您确定要删除该学生信息吗？</h5>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light" data-bs-dismiss="modal">
                                                    关闭
                                                </button>
                                                <input id="confirm_delete" type="button" class="btn btn-outline-light"
                                                       value="确认">
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->
                </div> <!-- end row-->
            </div>
            <!-- end row-->

        </div>
        <!-- container -->

    </div>
    <!-- content -->
{% endblock %}
<!-- END wrapper -->
{% block js %}
    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
    <script type="text/javascript">
        let EDIT_ID = null;
        $(function () {
            // 点击删除的方法
            bindBtnDelete();
            // 确认删除
            bindBtmConfirmDelete();
            // 由于【编辑】和【新增】是用的同一个模态框，所以得对他们进行判断
            binBtnSave();
            // 添加新员工 -- 模态框
            bindBtnAddEvent();
            binBtnEdit();
        })


        // 保存按钮函数：判断当前EDIT_ID的值，如果不为空则进行编辑函数，如果为空则进行添加函数
        function binBtnSave() {
            $('#btnSave').click(function () {
                $(".s_error").empty();
                if (EDIT_ID) {
                    doEdit();
                } else {
                    doAdd();
                }
            })
        }

        // 具体实现新增的函数 doAdd
        function doAdd() {
            $.ajax({
                url: '/teacher/add/',
                type: 'post',
                data: $('#addForm').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        alert('添加成功！')
                        location.reload();
                    } else {
                        $.each(res.error, function (name, data) {
                            $('#id_' + name).next().text(data[0])
                        })
                    }
                }
            })
        }

        // 添加新员工 -- 模态框
        function bindBtnAddEvent() {
            $('.btn-function').click(function () {
                $(".s_error").empty();
                // 首先将编辑的id置空 因为编辑和新增用的是用一个模态框
                EDIT_ID = undefined;
                // 新增之前先清除模态框表单内容
                $('#addForm')[0].reset()
            })
        }

        // 获取当前要编辑的学生的数据
        function binBtnEdit() {
            $('.btnEdit').click(function () {
                // 编辑之前先清除之前模态框表单内容
                $('#addForm')[0].reset();
                EDIT_ID = $(this).data('eid');
                // alert(EDIT_ID)
                $.ajax({
                    url: '/get/edit_detail/',
                    type: 'get',
                    data: {
                        eid: EDIT_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            $('#multiple-oneModalLabel').text('编辑')
                            // 将原本的数据在编辑框上显示出来
                            $.each(res.data, function (name, value) {
                                $('#id_' + name).val(value)
                                // 修改标题文字
                            })
                        } else {
                            alert(res.error)
                        }
                    }
                })
            })
        }

        // 编辑 函数
        function doEdit() {
            $.ajax({
                url: '/teacher/student_edit/' + '?eid=' + EDIT_ID,
                type: 'post',
                data: $('#addForm').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        alert('编辑成功！')
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips)
                        } else {
                            $.each(res.error, function (name, data) {
                                $('#id_' + name).next().text(data[0])
                            })
                        }

                    }
                }
            })
        }

        // 点击删除按钮的同时获取当前id
        function bindBtnDelete() {
            $('body').on('click', '.btnDelete', function () {
                // 获取当前这一行的 id 并传递给 bindBtmConfirmDelete 函数使用
                let deleteId = $(this).data('id');
                bindBtmConfirmDelete(deleteId);
            });
        }

        // 确认删除
        function bindBtmConfirmDelete(id) {
            $('#confirm_delete').click(function () {
                // 将 id 发送到后端
                $.ajax({
                    url: '/teacher/delete/',
                    method: "GET",
                    data: {
                        did: id
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload()
                        } else {
                            alert(res.error);
                            location.reload()
                        }
                    }
                })
            });
        }
    </script>
{% endblock %}