Graduate/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve
from django.urls import path, include, re_path
from Graduate import settings
from Graduate.settings import MEDIA_ROOT
from app01.views.everyone import login, register
from app01.views.student import student, student_echarts
from app01.views.teacher import teacher, teacher_echarts, teacher_notice
from app01.views.tools import tools
from app01.views.tools import *

urlpatterns = [
                  path('', login.login),
                  re_path(r'^api/', include('app01.api-urls')),
                  path("admin/", admin.site.urls),
                  path('register/', register.register),
                  path('error/', tools.error),
                  path('captcha/', include('captcha.urls')),
                  path('refresh_captcha/', tools.refresh_captcha, name='refresh_captcha'),
                  # 学生登录页面
                  path('student/index/', student.stu_index),
                  path('student/edit/password/', student.student_edit_password),
                  path("student/forgetpasswd/", student.student_forgetpasswd),
                  path('reset-student-password/<str:uidb64>/<str:token>/', student.reset_password,
                       name='reset-student-password'),
                  path('logout/', tools.logout),
                  path('student/china/', student_echarts.student_china),
                  path('student/get/china/data/', student_echarts.student_get_china_data),
                  path('student/notice/', student.student_notice),
                  path('student/get/notice/', student.student_get_notice),
                  path('student/xinzi/', student.xinzi),
                  path('student/dataTable/', student.dataTable),
                  path("student/dataView/", student.dataView),
                  path('student/chartsSkill/', student.chartsSkill),
                  path('student/chartsTags/', student.chartsTags),
                  path('student/chartsAddr/', student.chartsAddr),
                  path('student/chartsCompany/', student.chartsCompany),
                  path('student/kaoyan/', student.kaoyan),
                  path('student/calendar/', student.calendar),

                  # 学生清除红点
                  path('student/clear_notice/', student.student_clear_notice),
                  # 教师登陆
                  path('teacher/login/', teacher.teacher_login),
                  path("teacher/forgetpasswd/", teacher.teacher_forgetpasswd),
                  path('reset-teacher-password/<str:uidb64>/<str:token>/', teacher.reset_password,
                       name='reset-teacher-password'),
                  path('teacher_index/', teacher.teacher_index),
                  # 教师查看学生信息
                  path('teacher_student_views/', teacher.teacher_student_views),
                  path('teacher/edit/password/', teacher.teacher_edit_password),
                  path('teacher/add/', teacher.add_student),
                  path('teacher/delete/', teacher.delete_student),
                  path('get/edit_detail/', teacher.get_edit_detail),
                  path('teacher/student_edit/', teacher.teacher_student_edit),
                  # 教师管理班级信息
                  path('teacher_classes_views/', teacher.teacher_classes_views),
                  path('teacher/add/class/', teacher.add_class),
                  path('teacher/classes/delete/', teacher.delete_class),
                  path('get/classes/edit_detail/', teacher.get_classes_edit_detail),
                  path('teacher/classes_edit/', teacher.teacher_classes_edit),
                  # 教师页面查看班级以及学生的详情表
                  path('students/echarts/', teacher_echarts.students_echarts),
                  path('teacher_manage_classes/', teacher_echarts.teacher_manage_classes),
                  path('teacher_classes_status/', teacher_echarts.teacher_classes_status),
                  path('teacher/china/', teacher_echarts.teacher_china),
                  path('teacher/get/china/data/', teacher_echarts.teacher_get_china_data),
                  # 教师发布通知和管理通知
                  path('teacher/add/notice/', teacher_notice.add_notice),
                  path('teacher_manage/notice/', teacher_notice.manage_notice),
                  path('teacher/get/notice/edit_detail/', teacher_notice.get_notice_edit_detail),
                  path('teacher/notice/edit/', teacher_notice.teacher_notice_edit),
                  path('teacher/notice/delete/', teacher_notice.teacher_notice_delete),
                  # path(r'^static/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
                  path('static/<path:path>', serve, {'document_root': MEDIA_ROOT})
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = register.page_not_found

app01/models.py
from django.contrib.auth.hashers import make_password, check_password
from django.db import models

role = (
    (0, '老师'),
    (1, '学生'),
)


class Teacher(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=50, unique=True)
    phone = models.CharField(max_length=50, verbose_name='手机号', unique=True)
    password = models.CharField(verbose_name='密码', max_length=100)
    email = models.EmailField(null=True, blank=True, unique=True)
    avatar = models.ImageField(upload_to='teacher_images', null=True, blank=True, verbose_name='头像')
    role = models.IntegerField(verbose_name='角色', choices=role, default=0)
    last_login = models.DateTimeField(null=True, blank=True)

    def get_email_field_name(self):
        return 'email'

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "老师"
        verbose_name_plural = "老师"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)


class Class(models.Model):
    name = models.CharField(verbose_name='班级名', max_length=50, unique=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="负责的老师")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "班级"
        verbose_name_plural = "班级"


provinces = (
    (0, '北京市'),
    (1, '天津市'),
    (2, '河北省'),
    (3, '山西省'),
    (4, '内蒙古自治区'),
    (5, '辽宁省'),
    (6, '吉林省'),
    (7, '黑龙江省'),
    (8, '上海市'),
    (9, '江苏省'),
    (10, '浙江省'),
    (11, '安徽省'),
    (12, '福建省'),
    (13, '江西省'),
    (14, '山东省'),
    (15, '河南省'),
    (16, '湖北省'),
    (17, '湖南省'),
    (18, '广东省'),
    (19, '广西壮族自治区'),
    (20, '海南省'),
    (21, '重庆市'),
    (22, '四川省'),
    (23, '贵州省'),
    (24, '云南省'),
    (25, '西藏自治区'),
    (26, '陕西省'),
    (27, '甘肃省'),
    (28, '青海省'),
    (29, '宁夏回族自治区'),
    (30, '新疆维吾尔自治区'),
    (31, '台湾省'),
    (32, '香港特别行政区'),
    (33, '澳门特别行政区')
)


class Student(models.Model):
    student_no = models.CharField(max_length=50, unique=True, verbose_name='学号')
    username = models.CharField(max_length=50, verbose_name='用户名')
    phone = models.CharField(max_length=50, verbose_name='手机号', unique=True)
    password = models.CharField(max_length=100, verbose_name='密码')
    email = models.EmailField(null=True, blank=True, unique=True)
    classs = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='students', verbose_name='所在班级')
    avatar = models.ImageField(upload_to='app01/', default='app1/default_avatar.jpg', null=True, blank=True,
                               verbose_name='头像')
    status = models.IntegerField(verbose_name="毕业去向", choices=((0, '就业'), (1, '升学')), default=0)
    role = models.IntegerField(verbose_name='角色', choices=role, default=1)
    province = models.IntegerField(verbose_name='意向地区', choices=provinces, default=16)
    is_read = models.IntegerField(verbose_name="已未读", choices=((0, '未读'), (1, '已读')), default=0)
    last_login = models.DateTimeField(null=True, blank=True)

    def get_email_field_name(self):
        return 'email'

    def __str__(self):
        return self.student_no

    class Meta:
        verbose_name = "学生"
        verbose_name_plural = "学生"

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)


class Notice(models.Model):
    title = models.CharField(verbose_name="标题", max_length=200)
    content = models.TextField(verbose_name="内容")
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='notices')
    classes = models.ManyToManyField(Class, related_name='notices', verbose_name='班级')
    created_at = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "通知"
        verbose_name_plural = "通知"



class JobInfo(models.Model):
    # model自增字段
    id = models.AutoField('id', primary_key=True)
    title = models.CharField('岗位名字', max_length=255, default='')
    address = models.CharField('省份', max_length=255, default='')
    type = models.CharField('职业', max_length=255, default='')
    educational = models.CharField('学历', max_length=255, default='')
    workExperience = models.CharField('工作经历', max_length=255, default='')
    workTag = models.CharField('工作标签', max_length=2555, default='')
    salary = models.CharField('薪资', max_length=255, default='')
    salaryMonth = models.CharField('年终奖', max_length=255, default='')
    companyTags = models.CharField('公司福利', max_length=2555, default='')
    hrWork = models.CharField('人事职位', max_length=255, default='')
    hrName = models.CharField('人事名字', max_length=255, default='')
    pratice = models.BooleanField('是否为实习单位', max_length=255, default='')
    companyTitle = models.CharField('公司名称', max_length=255, default='')
    companyAvatar = models.CharField('公司头像', max_length=255, default='')
    companyNature = models.CharField('公司性质', max_length=255, default='')
    companyStatus = models.CharField('公司状态', max_length=255, default='')
    companyPeople = models.CharField('公司人数', max_length=255, default='')
    detailUrl = models.CharField('详情地址', max_length=2555, default='')
    companyUrl = models.CharField('公司详情地址', max_length=2555, default='')
    createTime = models.DateField('创建时间', auto_now_add=True)
    dist = models.CharField('行政区', max_length=255, default='')

    def toDict(self):
        return {'title': self.title, 'address': self.address, 'type': self.type, 'educational': self.educational,
                'workExperience': self.workExperience, 'workTag': self.workTag, 'salary': self.salary,
                'salaryMonth': self.salaryMonth, 'companyTags': self.companyTags,'hrName': self.hrName.strip(self.hrWork),
                'hrWork': self.hrWork, 'pratice': self.pratice,'companyTitle': self.companyTitle,
                'companyAvatar': self.companyAvatar,'companyNature': self.companyNature, 'companyStatus': self.companyStatus,
                'companyPeople': self.companyPeople,'detailUrl':self.detailUrl,'companyUrl':self.companyUrl,
                'dist':self.dist}

    # 数据库的表名称
    class Meta:
        verbose_name = "招聘信息"
        verbose_name_plural = "招聘信息"


class School(models.Model):
    name = models.CharField(verbose_name="院校名称", max_length=32, null=True)
    location = models.CharField(verbose_name="所在地", max_length=32, null=True)
    department = models.CharField(verbose_name="院校隶属", max_length=32, null=True)
    department_choices = (

        (1, "研究生院"),
        (0, " ")
    )
    is_research = models.BooleanField(verbose_name="是否有研究生院", choices=department_choices, max_length=32,
                                      null=True)
    line_choices = (

        (1, "自划线"),
        (0, " ")
    )
    is_auto_line = models.BooleanField(verbose_name="是否为自划线院校", choices=line_choices, max_length=32, null=True)
    double_choices = (
        (1, "双一流"),
        (0, " ")
    )
    is_double_one = models.BooleanField(verbose_name="是否为双一流院校", choices=double_choices, max_length=32,
                                        null=True)
    icon = models.CharField(verbose_name="图标链接", max_length=255, default='')
    url = models.CharField(verbose_name="院校链接", max_length=255, default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "院校"
        verbose_name_plural = verbose_name

app01/templates/student/calendar.html
{% extends 'student/student_layout.html' %}
{% load static %}
{% block content %}
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

        <!-- Fullcalendar css -->
        <link href="{% static 'assets/vendor/fullcalendar/main.min.css' %}" rel="stylesheet" type="text/css" />

        <!-- Theme Config Js -->
        <script src="{% static 'assets/js/config.js' %}"></script>

        <!-- App css -->
        <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

        <!-- Icons css -->
        <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/vendor/fullcalendar/main.min.css' %}" rel="stylesheet" type="text/css" />




            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box justify-content-between d-flex align-items-md-center flex-md-row flex-column">
                                    <h4 class="page-title">Calendar</h4>
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Jidox</a></li>
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">Apps</a></li>
                                        <li class="breadcrumb-item active">Calendar</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->

                        <div class="row">
                            <div class="col-12">

                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <div class="d-grid">
                                                    <button class="btn btn-lg fs-16 btn-danger" id="btn-new-event">
                                                        <i class="ri-add-circle-fill"></i> Create New Event
                                                    </button>
                                                </div>
                                                <div id="external-events" class="mt-3">
                                                    <p class="text-muted">Drag and drop your event or click in the calendar</p>
                                                    <div class="external-event bg-success-subtle text-success" data-class="bg-success"><i class="ri-focus-fill me-2 vertical-middle"></i>New Theme Release</div>
                                                    <div class="external-event bg-info-subtle text-info" data-class="bg-info"><i class="ri-focus-fill me-2 vertical-middle"></i>My Event</div>
                                                    <div class="external-event bg-warning-subtle text-warning" data-class="bg-warning"><i class="ri-focus-fill me-2 vertical-middle"></i>Meet manager</div>
                                                    <div class="external-event bg-danger-subtle text-danger" data-class="bg-danger"><i class="ri-focus-fill me-2 vertical-middle"></i>Create New theme</div>
                                                </div>

                                                <div class="mt-5 d-none d-xl-block">
                                                    <h5 class="text-center">How It Works ?</h5>

                                                    <ul class="ps-3">
                                                        <li class="text-muted mb-3">
                                                            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                                        </li>
                                                        <li class="text-muted mb-3">
                                                            Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage.
                                                        </li>
                                                        <li class="text-muted mb-3">
                                                            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                                                        </li>
                                                    </ul>
                                                </div>

                                            </div> <!-- end col-->

                                            <div class="col-lg-9">
                                                <div class="mt-4 mt-lg-0">
                                                    <div id="calendar"></div>
                                                </div>
                                            </div> <!-- end col -->

                                        </div> <!-- end row -->
                                    </div> <!-- end card body-->
                                </div> <!-- end card -->

                                <!-- Add New Event MODAL -->
                                <div class="modal fade" id="event-modal" tabindex="-1">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <form class="needs-validation" name="event-form" id="form-event" novalidate>
                                                <div class="modal-header py-3 px-4 border-bottom-0">
                                                    <h5 class="modal-title" id="modal-title">Event</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body px-4 pb-4 pt-0">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <div class="mb-3">
                                                                <label class="control-label form-label">Event Name</label>
                                                                <input class="form-control" placeholder="Insert Event Name" type="text" name="title" id="event-title" required />
                                                                <div class="invalid-feedback">Please provide a valid event name</div>
                                                            </div>
                                                        </div>
                                                        <div class="col-12">
                                                            <div class="mb-3">
                                                                <label class="control-label form-label">Category</label>
                                                                <select class="form-select" name="category" id="event-category" required>
                                                                    <option value="bg-danger" selected>Danger</option>
                                                                    <option value="bg-success">Success</option>
                                                                    <option value="bg-primary">Primary</option>
                                                                    <option value="bg-info">Info</option>
                                                                    <option value="bg-dark">Dark</option>
                                                                    <option value="bg-warning">Warning</option>
                                                                </select>
                                                                <div class="invalid-feedback">Please select a valid event category</div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-6">
                                                            <button type="button" class="btn btn-danger" id="btn-delete-event">Delete</button>
                                                        </div>
                                                        <div class="col-6 text-end">
                                                            <button type="button" class="btn btn-light me-1" data-bs-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-success" id="btn-save-event">Save</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div> <!-- end modal-content-->
                                    </div> <!-- end modal dialog-->
                                </div>
                                <!-- end modal-->
                            </div>
                            <!-- end col-12 -->
                        </div> <!-- end row -->

                    </div> <!-- container -->

                </div> <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <script>document.write(new Date().getFullYear())</script> © Jidox - Coderthemes.com
                            </div>
                            <div class="col-md-6">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">About</a>
                                    <a href="javascript: void(0);">Support</a>
                                    <a href="javascript: void(0);">Contact Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>







    <script src="{% static 'assets/js/vendor.min.js' %}"></script>

        <!-- Fullcalendar js -->
        <script src="{% static 'assets/vendor/fullcalendar/main.min.js' %}"></script>

        <!-- Calendar App Demo js -->
        <script src="{% static 'assets/js/pages/demo.calendar.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'assets/js/app.min.js' %}"></script>


{% endblock %}

app01/templates/student/kaoyan.html
{% extends 'student/student_layout.html' %}
{% load static %}
{% block content %}
    {#    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %} ">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %} ">
    <style>
        :root {
            --ct-menu-item-font-size: 1.5rem;
        }

        .button-toggle-menu {
            position: absolute; /* 或 relative; */
            left: 8px; /* 向左移动60像素 */
        }
        ol, ul {
    padding-left: 105rem;
}

    </style>




    <div class="content-page">
    <div class="content">
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box justify-content-between d-flex align-items-md-center flex-md-row flex-column">
                    <h4 class="page-title">考研信息</h4>
                    <ol class="breadcrumb m-0">

                    </ol>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">


                <div style="margin-bottom: 10px" class="clearfix">
                    <div class="row" style="height: 50px;">
                        <div class="col-sm-6">
                            <div style="height: 10px;width: 330px">
                                <form method="get" style="float:left;height: 25px">
                                    <label for="location">地区选择:</label>
                                    <label>
                                        <select name="location">
                                            <option value="">All</option>
                                            {% for location in locations %}
                                                <option value="{{ location }}">{{ location }}</option>
                                            {% endfor %}
                                        </select>
                                    </label>
                                    <button type="submit" style="border-radius: 5px;height: 25px">提交</button>
                                </form>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div style="float: right;width: 300px;">
                                <div style="float: right;width: 300px;">
                                    <form method="get">
                                        <div class="input-group">
                                            <input type="text" name="q" class="form-control"
                                                   placeholder="请输入学校名称或位置"
                                                   value="{{ search_data }}">
                                            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for school in queryset %}
                            <div class="col-sm-4">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div style="height: 100px;width: 330px">
                                            <div class="name" style="display: flex; align-items: center;">
                                                <img src='{{ school.icon }}' alt=""
                                                     style=" width: 90px;height: 90px;margin-top: 5px">
                                                <div>
                                                    <h4 style="margin-top: 0;text-align: center">
                                                        <a href="{{ link }}{{ school.url }}"
                                                           target="_blank">{{ school.name }}</a>
                                                    </h4>
                                                    <h5 style="text-align: center">位置:{{ school.location }}</h5>
                                                    <h5 style="text-align: center">隶属:{{ school.department }}</h5>
                                                    <h6 style="text-align: center;background: #EBF4FB;color: #1887E0;margin: 0">
                                                        {% if school.is_research %}
                                                            {{ school.get_is_research_display }}
                                                        {% endif %}
                                                        {% if school.is_auto_line %}
                                                            {% if school.is_research %}|{% endif %}
                                                            {{ school.get_is_auto_line_display }}
                                                        {% endif %}
                                                        {% if school.is_double_one %}
                                                            {% if school.is_research or school.is_auto_line %}|
                                                            {% endif %}
                                                            {{ school.get_is_double_one_display }}
                                                        {% endif %}
                                                    </h6>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        {% endfor %}
                    </div>

                    <div class="clearfix">
                        <ul class="pagination">
                            {{ page_string }}
                        </ul>

                    </div>


                </div>


            </div> <!-- container -->

        </div> <!-- content -->

        <!-- Footer Start -->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © HUAT - www.huat.edu.cn
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->

    </div>
    </div>
    </div>

{% endblock %}